services:
  db_svc:
    image: postgres:17
    container_name: db_postgresql
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: neron123
      POSTGRES_DB: dbtrustbank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/POSTGRES/data

  db_user_springboot:
    container_name: db_user_springboot
    build:
      context: ./user/db_user_svc/
      dockerfile: Dockerfile
    depends_on: 
      - db_svc
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=neron123
      - POSTGRES_DB=dbtrustbank
      - SPRING_DATASOURCE_URL=jdbc:POSTGRES://db_svc:5432/dbtrustbank
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=neron123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.POSTGRESDialect
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
    ports:
      - "8888:8888"

  svc_user_springboot:
    container_name: svc_user_springboot
    build:
      context: ./user/svc_user_svc/
      dockerfile: Dockerfile
    depends_on:
      - db_user_springboot
    ports:
      - "8787:8787"

  bff_user_springboot:
    container_name: bff_user_springboot
    build:
      context: ./user/bff_user_svc/
      dockerfile: Dockerfile
    depends_on:
      - svc_user_springboot
    ports:
      - "8686:8686"
    
  db_account_springboot:
    container_name: db_account_springboot
    build:
      context: ./account/db_account_svc/
      dockerfile: Dockerfile
    depends_on:
      - db_svc
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=neron123
      - POSTGRES_DB=dbtrustbank
      - SPRING_DATASOURCE_URL=jdbc:POSTGRES://db_svc:5432/dbtrustbank
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=neron123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.POSTGRESDialect
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
    ports:
      - "8585:8585"

  svc_account_springboot:
    container_name: svc_account_springboot
    build:
      context: ./account/svc_account_svc/
      dockerfile: Dockerfile
    depends_on:
      - db_account_springboot
    ports:
      - "8484:8484"

  bff_account_springboot:
    container_name: bff_account_springboot
    build:
      context: ./account/bff_account_svc/
      dockerfile: Dockerfile
    depends_on:
      - svc_account_springboot
    ports:
      - "8383:8383"

  db_transfer_springboot:
    container_name: db_transfer_springboot
    build:
      context: ./transfer/db_transfer_svc/
      dockerfile: Dockerfile
    depends_on:
      - db_svc
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=neron123
      - POSTGRES_DB=dbtrustbank
      - SPRING_DATASOURCE_URL=jdbc:POSTGRES://db_svc:5432/dbtrustbank
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=neron123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.POSTGRESDialect
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
    ports:
      - "8282:8282"

  svc_transfer_springboot:
    container_name: svc_transfer_springboot
    build:
      context: ./transfer/svc_transfer_svc/
      dockerfile: Dockerfile
    depends_on:
      - db_transfer_springboot
    ports:
      - "8181:8181"

  bff_transfer_springboot:
    container_name: bff_transfer_springboot
    build:
      context: ./transfer/bff_transfer_svc/
      dockerfile: Dockerfile
    depends_on:
      - svc_transfer_springboot
    ports:
      - "8080:8080"

volumes:
  postgres_data: